# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04' # examples of other options: 'macOS-10.13', 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'
  version: '1.0'

steps:
- script: dotnet restore
  displayName: 'dotnet restore NuGet'

# building by using dotnet build command
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  
# Or
# building by using .NET Core task
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration Release' # Update this to match your need

# ...
# do this after other tasks such as building
- task: DotNetCoreCLI@2
  displayName: Tests
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)--collect "Code coverage"'    

# published the output of your build to ArtifactStagingDirectory
- script: dotnet publish --output $(Build.ArtifactStagingDirectory)
  displayName: Publish

# publish artifacts to Azure Pipelines
# do this near the end of your pipeline in most cases
- task: PublishBuildArtifacts@1

# publish to a NuGet feed
# do this near the end of your pipeline in most cases
# - script: dotnet pack /p:PackageVersion=$(version)
- task: NuGetCommand@2
  inputs:
    command: pack
    # packagesToPack: The path to the files that describe the package you want to create.
    packagesToPack: '**/*.csproj'
    # configuration: The default is $(BuildConfiguration) unless you want to always build either Debug or Release packages, 
    # or unless you have a custom build configuration.
    # packDestination: The default is $(Build.ArtifactStagingDirectory). If you set this, make a note of the location so you can use it in the 
    # publish task.
